# Please copy this example config to config.yaml
# and adjust it to your needs.

# This is useful to differentiate multiple flaxdog
# instances monitoring multiple harvesters
notification_title_prefix: 'Flax'
log_level: INFO

# Only one consumer can be enabled at a time, you can
# delete the section for the consumer which you aren't using
# For Windows file path needs to be absolute.
flax_logs:
  file_log_consumer:
    enable: true
    file_path: '~/.flax/mainnet/log/debug.log'
  network_log_consumer:
    enable: false
    remote_file_path: '~/.flax/mainnet/log/debug.log'
    remote_host: "192.168.0.100"
    remote_user: "flax"
    remote_port: 22

# Enable this and flaxdog will ping a remote server every 5 minutes
# That way you can know that the monitoring is running as expected
keep_alive_monitor:
  enable_remote_ping: false
  ping_url: ''

# Enable this and you'll receive a daily summary notification
# on your farm performance at the specified time of the day.
daily_stats:
  enable: true
  time_of_day: 21
  frequency_hours: 24

# We support a lot of notifiers, please check the README for more
# information. You can delete the sections which you aren't using.
# You can also enable more than one notifier and send different
# notifications to each of them. E.g. enable daily_stats only to E-mail.
# If you enable wallet_events you'll get notifications anytime your
# wallet receives some XFX (e.g. farming reward).
notifier:
  pushover:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      api_token: 'dummy_token'
      user_key: 'dummy_key'
  telegram:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      bot_token: 'dummy_bot_token'
      chat_id: 'dummy_chat_id'
  smtp:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      sender: 'flax@example.com'
      sender_name: 'flaxdog'
      recipient: 'you@example.com'
      username_smtp: 'username'
      password_smtp: 'password'
      host: 'smtp.example.com'
      port: 587
  script:
    enable: false
    daily_stats: true
    wallet_events: true
    script_path: 'tests/test_script.sh'
  discord:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      webhook_url: 'https://discord.com/api/webhooks/...'
  slack:
    enable: false
    daily_stats: true
    wallet_events: true
    credentials:
      webhook_url: 'https://hooks.slack.com/services/...'
  mqtt:
    enable: false
    daily_stats: true
    wallet_events: true
    topic: flax/flaxdog/alert
    qos: 1
    retain: false
    credentials:
      host: '192.168.0.10'
      port: 8883
      username: ''
      password: ''
